// LOCALHOST
### create e_cards
curl -X POST http://localhost:8080/api/ecards \
-H "Content-Type: application/json" \
-d '{
  "firstName": "Hope",
  "middleName": "A",
  "lastName": "Simon",
  "occupation": "Software Engineer",
  "position": "Developer",
  "officeAddress": "123 Tech Street",
  "headquartersLocation": "Tech City HQ",
  "subBusinessBranches": ["Branch 1", "Branch 2"],
  "contactNumber": "+1234567890",
  "email": "hopesimon@gmail.com",
  "socialMediaHandles": {
    "linkedin": "linkedin.com/in/hopesimon",
    "twitter": "twitter.com/hopesimon"
  },
  "passportPhotograph": "base64ImageString"
}'

### get all e_cards
GET http://localhost:8080/api/ecards

### get e_cards by id
GET http://localhost:8080/api/ecards/666047486e1f814575eb9353

### update E_card
curl -X PUT http://localhost:8080/api/ecards/666047486e1f814575eb9353 \
-H "Content-Type: application/json" \
-d '{
  "firstName": "John",
  "middleName": "B",
  "lastName": "Doe",
  "occupation": "Data Scientist",
  "position": "Senior Analyst",
  "officeAddress": "456 Data Avenue",
  "headquartersLocation": "Data City HQ",
  "subBusinessBranches": ["Branch 3", "Branch 4"],
  "contactNumber": "+9876543210",
  "email": "johndoe@example.com",
  "socialMediaHandles": {
    "linkedin": "linkedin.com/in/johndoe",
    "twitter": "twitter.com/johndoe"
  },
  "passportPhotograph": "newBase64ImageString"
}'


### delete a E_card
DELETE http://localhost:8080/api/ecards/666047486e1f814575eb9353












































POST http://localhost:8080/e_cards
Content-Type: application/json

{
  "firstName": "Hope",
  "lastName": "Simon",
  "email": "hopesimon@gmail.com.com",
  "favoriteColor": "Green",
  "birthday": "1999-01-15"
}


### get all e_cards
GET http://localhost:8080/e_cards

### get e_cards by id
GET http://localhost:8080/e_cards/6660074391243103ae715d7c
###
GET http://localhost:8080/e_cards/65172c7cba9e5547e327e23c
###
GET http://localhost:8080/e_cards/651732d2bc9d5f52dffce548
###
###
GET http://localhost:8080/e_cards/651be5e903ac3bd725aba32b

### 
GET http://localhost:8080/e_cards/651be3845175afdc2a9ee53d

### 
GET http://localhost:8080/e_cards/651d3d27a0f7f887db3eaac5

### 
GET http://localhost:8080/e_cards/651d4299450bf499c49dd913

### 
GET http://localhost:8080/e_cards/651d8200cb4f80947149c900

### 
GET http://localhost:8080/e_cards/651d820ccb4f80947149c901

### update contact
PUT http://localhost:8080/e_cards/6660074391243103ae715d7c
Content-Type: application/json

{
  "firstName": "Dorathy",
  "lastName": "Mustapha",
  "email": "dorathy@gmail.com.com",
  "favoriteColor": "Darkblue",
  "birthday": "2001-01-15"
}

### delete a contact
DELETE http://localhost:8080/e_cards/6660074391243103ae715d7c


// production
### Create a New Contact (POST):
curl -X POST -H "Content-Type: application/json" -d '{
  "firstName": "Solomon",
  "lastName": "Josiah",
  "email": "solomon@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}' https://cse341-4.onrender.com/e_cards'

###Read All e_cards (GET):
curl  https://cse341-3.onrender.com/e_cards

###Read a Contact by ID (GET):
curl  https://cse341-3.onrender.com/e_cards/65172c7bba9e5547e327e239

### Update a Contact by ID (PUT):
curl -X PUT -H "Content-Type: application/json" -d '{
  "firstName": "Michael",
  "lastName": "Amos",
  "email": "moseschris@gmail.com",
  "favoriteColor": "White",
  "birthday": "1995-02-15"
}' https://cse341-3.onrender.com/e_cards/6520765f06fa9083db2c5581



### Delete a Contact by ID (DELETE):
curl -X DELETE https://cse341-3.onrender.com/e_cards/65172c7bba9e5547e327e239





