// LOCALHOST
### create contacts
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Hope",
  "lastName": "Simon",
  "email": "hopesimon@gmail.com.com",
  "favoriteColor": "Green",
  "birthday": "1999-01-15"
}


### get all contacts
GET http://localhost:8080/contacts

### get contacts by id
GET http://localhost:8080/contacts/65172c7bba9e5547e327e239
###
GET http://localhost:8080/contacts/65172c7cba9e5547e327e23c
###
GET http://localhost:8080/contacts/651732d2bc9d5f52dffce548
###
###
GET http://localhost:8080/contacts/651be5e903ac3bd725aba32b

### 
GET http://localhost:8080/contacts/651be3845175afdc2a9ee53d

### 
GET http://localhost:8080/contacts/651d3d27a0f7f887db3eaac5

### 
GET http://localhost:8080/contacts/651d4299450bf499c49dd913

### 
GET http://localhost:8080/contacts/651d8200cb4f80947149c900

### 
GET http://localhost:8080/contacts/651d820ccb4f80947149c901

### update contact
PUT http://localhost:8080/contacts/652077a19dcf632d78324d90
Content-Type: application/json

{
  "firstName": "Dorathy",
  "lastName": "Mustapha",
  "email": "dorathy@gmail.com.com",
  "favoriteColor": "Darkblue",
  "birthday": "2001-01-15"
}

### delete a contact
DELETE http://localhost:8080/contacts/652077a19dcf632d78324d90


// production
### Create a New Contact (POST):
curl -X POST -H "Content-Type: application/json" -d '{
  "firstName": "Solomon",
  "lastName": "Josiah",
  "email": "solomon@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "1990-01-01"
}' https://cse341-4.onrender.com/contacts'

###Read All Contacts (GET):
curl  https://cse341-3.onrender.com/contacts

###Read a Contact by ID (GET):
curl  https://cse341-3.onrender.com/contacts/65172c7bba9e5547e327e239

### Update a Contact by ID (PUT):
curl -X PUT -H "Content-Type: application/json" -d '{
  "firstName": "Michael",
  "lastName": "Amos",
  "email": "moseschris@gmail.com",
  "favoriteColor": "White",
  "birthday": "1995-02-15"
}' https://cse341-3.onrender.com/contacts/6520765f06fa9083db2c5581



### Delete a Contact by ID (DELETE):
curl -X DELETE https://cse341-3.onrender.com/contacts/65172c7bba9e5547e327e239





